import type { NextPage } from 'next';
import Head from 'next/head';

import { Counter } from '../src/counter/components/counter';
import { WalletList } from '../src/web3/components/WalletList';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WalletList />
      <Counter />
    </div>
  );
};

export default Home;
