import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import { Counter } from "../src/counter/components/counter";
import { useStore } from "../src/store";
import { WalletList } from "../src/web3/components/WalletList";
import styles from "../styles/Home.module.css";
import {useAccount, useNetwork, useConfig} from 'wagmi';

const Home: NextPage = () => {
  const { connector: activeConnector, isConnected } = useAccount()
  const { chain, chains } = useNetwork()
  const { connector, publicClient } = useConfig()

  console.log('activeConnector', activeConnector)
  console.log('connector', connector)
  console.log('publicClient', publicClient)
  console.log('isConnected', isConnected)
  console.log('chain', chain)
  console.log('chains', chains)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WalletList />
      <Counter />
    </div>
  );
};

export default Home;
